# Generated by Django 5.0.2 on 2024-02-28 12:11

import appusers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=appusers.models.User.user_img_path, verbose_name='Фотография'),
        ),
    ]
