# Generated by Django 5.0.2 on 2024-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0002_alter_mountains_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountains',
            name='black',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сложные'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='blue',
            field=models.IntegerField(blank=True, default=0, verbose_name='Легкие'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='green',
            field=models.IntegerField(blank=True, default=0, verbose_name='Учебные'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='red',
            field=models.IntegerField(blank=True, default=0, verbose_name='Продвинутые'),
        ),
    ]
