# Generated by Django 5.0.2 on 2024-02-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0003_mountains_black_mountains_blue_mountains_green_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mountains',
            name='resort',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mountain', to='appmountain.resort'),
        ),
        migrations.AlterField(
            model_name='tagmountain',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
