# Generated by Django 5.0.2 on 2024-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0005_mountains_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountains',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Линк'),
        ),
    ]
