# Generated by Django 5.0.2 on 2024-02-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0006_alter_mountains_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagmountain',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
