# Generated by Django 5.0.2 on 2024-02-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0008_resort_description_alter_resort_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'verbose_name': 'Курорт', 'verbose_name_plural': 'Курорты'},
        ),
    ]
