# Generated by Django 5.0.2 on 2024-02-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0009_alter_resort_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountains',
            options={'ordering': ['title'], 'verbose_name': 'Гора', 'verbose_name_plural': 'Горы'},
        ),
    ]
