# Generated by Django 5.0.2 on 2024-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0010_alter_mountains_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountains',
            name='lift_baby',
            field=models.IntegerField(blank=True, default=0, verbose_name='Детские'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='lift_bugel',
            field=models.IntegerField(blank=True, default=0, verbose_name='Бугельные'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='lift_cabin',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кабинные'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='lift_chair',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кресельные'),
        ),
    ]
