# Generated by Django 5.0.2 on 2024-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0011_mountains_lift_baby_mountains_lift_bugel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountains',
            name='prices',
            field=models.TextField(blank=True, verbose_name='Цены'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='tracks',
            field=models.TextField(blank=True, verbose_name='Трассы'),
        ),
        migrations.AddField(
            model_name='mountains',
            name='work_time',
            field=models.TextField(blank=True, verbose_name='График Работы'),
        ),
    ]
