# Generated by Django 5.0.2 on 2024-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0013_mountains_tracks_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountains',
            name='season_time',
            field=models.TextField(blank=True, verbose_name='График Работы'),
        ),
    ]
