# Generated by Django 5.0.2 on 2024-02-28 08:03

import appmountain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0014_mountains_season_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountains',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=appmountain.models.Mountains.mountain_img_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mountains',
            name='season_time',
            field=models.TextField(blank=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='mountains',
            name='tracks_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=appmountain.models.Mountains.mountain_img_path, verbose_name='Схема трасс'),
        ),
    ]
