# Generated by Django 5.0.2 on 2024-02-28 08:12

import appmountain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0022_alter_mountains_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountains',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=appmountain.models.Mountains.mountain_img_path, verbose_name='Фото'),
        ),
    ]
