# Generated by Django 5.0.2 on 2024-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0023_alter_mountains_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountains',
            name='location',
            field=models.TextField(blank=True, default='', verbose_name='Локация'),
        ),
    ]
