# Generated by Django 5.0.2 on 2024-02-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmountain', '0024_mountains_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountains',
            name='distance',
        ),
    ]
